### ISSUE TITLE
How to increase size of labels in graph?

### ISSUE THREAD

**Issue by nitinjs** [NdubuisiJr/skia-chart#24]
How to increase size of labels in graph?
they look very small on android

![image](https://user-images.githubusercontent.com/298479/99522977-692bca00-29bc-11eb-9e45-05f13b166d6f.png)

**Comment by NdubuisiJr** [comment]
Hi @nitinjs 
Thanks for this question.

Currently, you can't change the size of the labels.

This feature and other new features will be released soon.

Thanks

**Comment by NdubuisiJr** [comment]
Hi @nitinjs 

I was about implementing this when I realized that it was already there :) 💯 

https://github.com/NdubuisiJr/skia-chart/blob/697678862333a92e8923400b4c622d8ffdc66240/SkiaChart/Views/ChartCanvas.cs#L160

You didn't find it because it is a dependency property. So you need to set it or bind to it on the `ChartCanvas`.

Cheers!!!
